[build]
  command = "npm run build"
  publish = ".next/standalone/public"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    appDir = true
    nodeVersion = "22"
    skipBuildFunctionsDir = false



